### ISSUE TITLE
Feature 5: User can sign up as a vendor

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create database for vendor signup
- [x] Update `data.sql` to create sample data for a vendor

### ☁️ Server Tasks

- [x] Update `server/index.js` to make a post request for a new vendor signup.
- [x] In the post request, use `argon2` to hash the password input.

### ⚡ Client Tasks

- [x] Create a `page` called `vendor-signup.jsx`.
- [x] Create a function called `ParseRoute` in the `lib directory` that will parse a route.
- [x] Import the `ParseRoute` in `App` component to store hash location.
- [x] In the `App` component, add a function that will render pages by hash routes.
- [x] Add hash routing to the `vendor anchor` in `home` page to redirect to the `vendor signup`.
- [x] Create a form so that a vendor can enter `first and last name`, `username`, `password`, `verify password` in the `vendor-signup` page.
- [x] Add styling to the form.
- [x] Make sure that the inputs for the `password` and `verification` matches before a vendor can complete signup.
- [x] Add a `submit` button that will `prevent default` when the form is submitted.
- [x] Make sure that the client is making a `POST` request to database.
- [x] Create a `page` for account creation (`vendor-success.jsx`) after a vendor signs up.
- [x] Display a message that sign up was a success and buttons to reroute to `home page` or `log in`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
