### ISSUE TITLE
Feature 6: User can sign in as a vendor

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create a `POST` request for `sign-in`.
- [x] Use `argon2` to verify username and `jwt` to generate token.
- [x] Test the `POST` request with `node` to make sure there are no errors.

### ⚡ Client Tasks

- [x] Create a new page `vendor-signin.jsx`.
- [x] Add hash routing to the anchors in `header` and `vendor-success` components.
- [x] Make sure that anchors are directing correctly.
- [x] Create a form so a vendor can sign in with `username` and `password`.
- [x] Add a `sign in` button at the bottom.
- [x] Add a `submit` listener to the form and `prevent default`.
- [x] Add `onChange` listeners for input changes.
- [x] Update the `POST` request on `vendor-signup` to initiate `signup`.
- [x] Add a `POST` request for `signin` to the form submission.
- [x] Go to `app.jsx` and add states `user: null`, `isAuthorizing: true` and function `handleSignIn`.
- [x] On success, clear out the values for `username` and `password`.
- [x] Create a new page `vendor-listing` and add a success message for signing in.
- [x] Go to `app.jsx` and add a conditionally render `vendor-home` when the hash is set to `vendor-home`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
