### ISSUE TITLE
Feature 8: User can post a new listing to database

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to import a new table for `listings`.
- [x] Update `data.sql` to import sample data for a listing.

### ☁️ Server Tasks

- [x] Create a new file `authorization-middleware.js`.
- [x] Define a function `authorizationMiddleware` to check for a token.
- [x] Import the `authorizationMiddleware` into `server/index.js`.
- [x] Update `server/index.js` to make a new `POST` request to the `listings` table.
- [ ] Test `POST` request in terminal.

### ⚡ Client Tasks

- [x] Add an anchor to the `sign up` page to redirect existing users to sign in page.
- [x] Add a new anchor to the nav bar and route to home page.
- [x] Go to the `vendor-signin` component and add a new anchor for new users.
- [x] Go to `vendor-home` page and create a mockup for new listing entry.
- [x] Add a submit button for form submission.
- [x] Create a submit function that will prevent default for a submission.
- [x] Add `onChange` event listeners and store these to states.
- [x] On submission, make a `POST` request for a new listing.
- [x] Make sure the request catches any errors.
- [x] Edit the nav bar to re-route to the `vendor home` page if current user has a token.
- [x] Create a new page `token-required.jsx`.
- [x] Conditionally render this page when there is no token.
- [x] Create a mockup for the page with anchors to redirect user.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by MattChau01** [comment]
`vendor-home` will conditionally render whether the vendor already uploaded a listing or not. (displays a brief summary of the listing)
