### ISSUE TITLE
Feature 9: User can see catalog of listings

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` with phone number.
- [x] Update `data.sql` with sample data for a room listing.

### ☁️ Server Tasks

- [x] Include `phone number` in the post request for new listing.
- [x] Test that the updated post request works.
- [x] Create a new `GET` request that gets data for all listings.
- [x] Test the `GET` request.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new page view `catalog.jsx`.
- [x] Add hash routing to the `participants` anchor on the `home` page and `header` to view `catalog` page.
- [x] Make sure the `participants` route works on every page.
- [x] Go to the `vendor-home` page and add a new input field for phone number.
- [x] Add a new state for `phoneNumber` and add `onChange` listener for this input field.
- [x] Update the `POST` request in the vendor home with a phone number field.
- [x] Go to the `catalog` page and make a mock up with the sample listing data.
- [x] Create a new page `listings-overview.jsx` and move the mockup into the component.
- [x] Add a hash router based off the `entryId` of a listing.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
