### ISSUE TITLE
Feature 10: User can edit their listing

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create a `GET` request to practice selecting a targeted `entryId`.
- [x] Create a `PATCH` request to modify a vendor listing.
- [x] Test that HTTP request works.

### ⚡ Client Tasks

- [x] Go to `vendor-listings.jsx` and add a button to edit.
- [x] Add a state `editClick` and assign initial state `false`.
- [x] Create a new function `editClicked` with prevent default and console log to test that the button is working.
- [x] Conditionally render a new page with an edit form.
- [x] Create a new component `edit-listing.jsx` and add boiler plate code.
- [x] Copy and paste form component from `new-listing-data.jsx` to see mockup.
- [x] Migrate fetch request from `vendor-listings.jsx` into `vendor-home.jsx` component and make sure there are no errors.
- [x] Create a second listing in the same account and make sure that the preview is independent from each other.
- [x] Stylize form to pre-load room data.
- [x] Add `onChange` listeners for each input.
- [x] Create a new component `edit-form.jsx` and import in `edit-listing.jsx`.
- [x] If the data is modified, initiate `PATCH` request. 
- [x] Make sure `PATCH` request works with no error in database and front end.
- [x] Remove unused `edit-listing` hash views from `App.jsx` and `edit-room.jsx` from `pages` directory.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by MattChau01** [comment]
Added conditional rendering on `vendor-home` component. Will work on editing an updating style for edit component.

**Comment by MattChau01** [comment]
Use `componentDidMount` to re render additional/new entries.

**Comment by MattChau01** [comment]
![image](https://github.com/MattChau01/escape-room/assets/113082803/acac7ef2-b951-49d8-a8e6-43f68f433442)


`https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable`

![image](https://github.com/MattChau01/escape-room/assets/113082803/16a58fde-60df-45fa-a74a-f5df4b7f56ca)

**Comment by MattChau01** [comment]
Will look into alternate way of editing:

- clicking on a specific field to edit(?)
- pre-load data onto a form

**Comment by MattChau01** [comment]
Will need to update the rendering of the `catalog` page. After updating a listing, the `catalog` page will read incorrect indexes and display the wrong listing when clicked.

[scrnli_7_11_2023_10-37-34 AM.webm](https://github.com/MattChau01/escape-room/assets/113082803/1f7c8435-3816-43d9-b531-177619d80b5a)
