### ISSUE TITLE
Feature 11: User can delete their listing

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#22]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create a `DELETE` request to delete a targeted `entryId`.
- [x] Test that the HTTP request works.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Go to `vendor-home` and add a new `div` with a delete button.
- [x] Create a new function `deleteListing` and add a listener to the button.
- [x] Insert a console log in the function to test the button works.
- [x] Add a state `deleteClicked` and set it to false then setState to `true` on click.
- [x] Conditionally render validation buttons when user clicks on `delete`.
- [x] Create a function `confirmDelete` and add a listener on the confirm button.
- [x] Add `setState { deleteClicked: false}` to the `submit` and `close` buttons on the edit form.
- [x] Add a fetch request for `DELETE` on the `confirmDelete` functionality.
- [ ] Make sure the delete works with no error.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
