### ISSUE TITLE
Refactor: Vendor home page

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#25]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Create a new component`new-listing-form.jsx`.
- [x] Move form from `vendor-home` to `new-listing-form.jsx` page.
- [x] Add the sign out button to the vendor home screen.
- [x] Add a button that will conditionally render the form when clicked.
- [x] Change the `difficulty` and `minimumPlayers` inputs into selection options and limit characters on `price`.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
