### ISSUE TITLE
Feature 12: User can view a list of listings they've posted (vendor side)

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#26]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create a `GET` request that will retrieve all listings posted by a specific user.
- [x] Test that this request works with no errors.

### ⚡ Client Tasks

- [x] Create a new component `vendor-listings` and define a new function `VendorListings`.
- [x] Add test content and import into `vendor-home`.
- [x] Add the React Hook: `useEffect`, call an anonymous function that will call a `GET` request using the `userId` from local storage as an argument.
- [x] Console.log the variable to test that listings are being stored properly.
- [x] Map through the variable to render all listings posted by the current user.
- [x] Stylize the list properly.
- [x] Conditionally render whether the logged user has any listings or not.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by MattChau01** [comment]
conditionally render a list whether `this.state.listings === []` or `this.state.listings.length === 0 `.
