### ISSUE TITLE
Feature 13: User can view more details on click (participant side)

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#28]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Test the `GET` request that retrieves all existing listings.
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client Tasks

- [x] Go to `app.jsx` and conditionally render the list.
- [x] Go to `room-details` to import the `Header` and make sure that navigation clicks are working properly.
- [x] Create a new file in the lib called `parse-room-details.js`.
- [x] Add functionality that will retrieve what room `ID` number is currently being viewed.
- [x] Import `parse-room-details` into `room-details` and test that the `roomId` is being retrieved.
- [x] Create a simple mockup for room details on the selected room.
- [x] Stylize the details on `room-details.jsx`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by MattChau01** [comment]
Orginal App bar component: 

```
      <AppBar className='drawer'>
        {/* <Toolbar style={{ backgroundColor: '#046290' }}> */}
        <div className='mx-2 my-2' style={{ backgroundColor: '#1976D2' }}>
          <IconButton
            color="inherit"
            aria-label="open drawer"
            edge="start"
            onClick={handleDrawerToggle}
            style={{
              outline: 'none'
            }} >
            <MenuIcon />
          </IconButton>

          <a style={{
            fontSize: '1.6rem',
            fontWeight: 500
          }}>
            {/* ESC Room Finder */}
            <span><img src={esc} alt='esc' style={{ width: '1.75rem', height: '1.75rem', marginBottom: '.25rem', marginLeft: '.5rem' }} /></span> Room Finder
          </a>

        </div>
        {/* </Toolbar> */}
      </AppBar>

```

**Comment by MattChau01** [comment]
esc icon:
```
https://www.flaticon.com/free-icon/escape_3602367?term=escape+button&page=1&position=5&origin=search&related_id=3602367
```
