### ISSUE TITLE
Polish: Home page components (accordion/carousel/layout)

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#37]
## ✅ Task List

> ##### Commit checklist for tasks needed.
- [x] Update the vendor setup in the `accordion` component.
- [x] Add an anchor tag in the `about us` section and in the app bar for the GitHub repo for this project.
- [x] Create a new page `About us` and add boiler plate code.
- [x] Create a function `aboutUs` in `app.jsx` that will be passed into `home` component.
- [x] Add a summary and include the repo link to this project.
- [x] Make sure to pass `aboutUs` throughout all header components.
- [x] Update the section on how to use this site in the `accordion` component.
- [x] Rearrange image carousel to be on top as a `hero` component with new images.
- [x] Make sure that the width is 100% and is contained within the div.
- [x] Update styling on arrow buttons.
- [x] Remove all commented code and console logs.
