### ISSUE TITLE
Polish 1: Ensure that listings are displayed correctly on updates (delete/patch requests)

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/escape-room#38]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Go to `catalog` page and check how listings are currently being rendered.
- [x] Create a new `GET` request that will target a selected entry by `entryId`. 
- [x] Delete all commented out code & console logs.
- [x] Change theme to the color: `#046290`.
